"use client";

import React, { useState } from "react";
import { FileCheck2, Download, ShieldCheck, Sparkles, AlertCircle, FileText } from "lucide-react";
import { api, API_BASE_URL } from "@/lib/api";

export default function ReportsPage() {
  const [generating, setGenerating] = useState(false);
  const [reportResult, setReportResult] = useState<any>(null);

  async function handleGenerateReport() {
    setGenerating(true);
    try {
      const res = await api.generateReport(1, "Winter Wheat (Triticum aestivum)");
      setReportResult(res);
    } catch (err) {
      console.warn("Report generation notice:", err);
    } finally {
      setGenerating(false);
    }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-slate-900">
          Certified Agronomic Audit & Compliance Reporting
        </h1>
        <p className="text-xs text-slate-500">
          Official agronomic verification certificates generated by ReportLab, sealed with cryptographic SHA-256 validation digests.
        </p>
      </div>

      {/* Generator Card */}
      <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm space-y-4">
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <div className="flex items-center gap-2">
            <FileCheck2 className="w-5 h-5 text-purple-700" />
            <h3 className="font-semibold text-slate-900 text-sm">Generate Institutional Agronomic Certificate</h3>
          </div>
          <span className="text-[11px] font-mono text-purple-800 bg-purple-50 px-2 py-0.5 rounded">
            PDF Standard • SHA-256 Sealed
          </span>
        </div>

        <p className="text-xs text-slate-500 leading-relaxed">
          The certified audit certificate compiles comprehensive farm telemetry, 4-qubit Hilbert quantum projections, Sentinel-2 vegetation canopy readings, precision nutrient application guidelines, and legal agronomic disclaimers into an official compliance document.
        </p>

        <div className="pt-2">
          <button
            onClick={handleGenerateReport}
            disabled={generating}
            className="inline-flex items-center gap-2 bg-purple-700 hover:bg-purple-800 text-white font-semibold text-xs px-4 py-2.5 rounded-xl shadow-sm transition-all disabled:opacity-50 cursor-pointer"
          >
            {generating ? (
              <>
                <Sparkles className="w-4 h-4 animate-spin" />
                <span>Compiling Cryptographic Audit PDF...</span>
              </>
            ) : (
              <>
                <FileText className="w-4 h-4" />
                <span>Generate Certified Agronomic Audit</span>
              </>
            )}
          </button>
        </div>

        {reportResult && (
          <div className="mt-4 p-5 bg-purple-50/50 rounded-xl border border-purple-200 text-xs space-y-3">
            <div className="flex items-center justify-between">
              <span className="font-semibold text-purple-950">{reportResult.title}</span>
              <span className="font-mono text-[10px] text-purple-700 bg-purple-100 px-2 py-0.5 rounded">
                Report #{reportResult.report_id}
              </span>
            </div>

            <p className="text-purple-900 leading-relaxed font-mono text-[11px] bg-white p-3 rounded-lg border border-purple-100">
              {reportResult.summary}
            </p>

            <div className="flex items-center justify-between pt-2">
              <span className="text-slate-400 font-mono text-[10px]">
                Generated: {new Date(reportResult.generated_at).toLocaleString()}
              </span>
              <a
                href={`${API_BASE_URL.replace("/api/v1", "")}${reportResult.download_pdf_url}`}
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-1.5 bg-purple-700 hover:bg-purple-800 text-white font-semibold text-xs px-3 py-1.5 rounded-lg transition-colors shadow-xs"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download Official PDF</span>
              </a>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
