"use client";

import React, { useState } from "react";
import Link from "next/link";
import {
  FileCheck2,
  Download,
  ShieldCheck,
  RefreshCw,
  AlertCircle,
  FileText,
  Check,
  Layers,
  MapPin,
  Sprout,
} from "lucide-react";
import { api, API_BASE_URL } from "@/lib/api";
import { useFarm } from "@/lib/FarmContext";

export default function ReportsPage() {
  const { farms, activeFarmId, setActiveFarmId, activeFarm } = useFarm();
  const [cropType, setCropType] = useState<string>("Winter Wheat (Triticum aestivum)");
  const [generating, setGenerating] = useState(false);
  const [reportResult, setReportResult] = useState<any>(null);

  // Section inclusion check options (checkboxes)
  const [incSummary, setIncSummary] = useState(true);
  const [incYield, setIncYield] = useState(true);
  const [incSatellite, setIncSatellite] = useState(true);
  const [incWeather, setIncWeather] = useState(true);
  const [incNutrients, setIncNutrients] = useState(true);
  const [incKernelMatrix, setIncKernelMatrix] = useState(false);
  const [incSha256, setIncSha256] = useState(true);

  async function handleGenerateReport() {
    if (farms.length === 0) return;
    setGenerating(true);
    try {
      const res = await api.generateReport(activeFarmId || farms[0].id, cropType);
      setReportResult(res);
    } catch (err) {
      console.warn("Report generation notice:", err);
    } finally {
      setGenerating(false);
    }
  }

  if (farms.length === 0) {
    return (
      <div className="p-4 sm:p-6 lg:p-8 max-w-7xl mx-auto space-y-6">
        <div className="bg-white rounded-2xl p-10 border border-slate-200 text-center space-y-4 shadow-sm">
          <div className="w-14 h-14 rounded-2xl bg-emerald-50 text-emerald-700 flex items-center justify-center mx-auto">
            <FileCheck2 className="w-7 h-7" />
          </div>
          <div className="space-y-1">
            <h2 className="text-xl font-bold text-slate-900">No Farm Available for Certified Reports</h2>
            <p className="text-xs text-slate-500 max-w-md mx-auto">
              Add your farm holding to generate official certified agronomic PDF audits with cryptographic SHA-256 validation digests.
            </p>
          </div>
          <div className="pt-2">
            <Link
              href="/dashboard/farms"
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-emerald-800 hover:bg-emerald-900 text-white font-bold text-xs transition cursor-pointer shadow-xs"
            >
              <Sprout className="w-4 h-4" />
              <span>Add My Farm</span>
            </Link>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h2 className="text-xl sm:text-2xl font-bold tracking-tight text-slate-900">
          Agricultural Report
        </h2>
        <p className="text-xs text-slate-500">
          Official agronomic verification certificates generated by ReportLab, sealed with cryptographic SHA-256 validation digests.
        </p>
      </div>

      {/* Generator Card */}
      <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm space-y-5">
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <div className="flex items-center gap-2">
            <FileCheck2 className="w-5 h-5 text-purple-700" />
            <h3 className="font-semibold text-slate-900 text-sm">Generate Institutional Agronomic Certificate</h3>
          </div>
          <span className="text-[11px] font-mono text-purple-800 bg-purple-50 px-2 py-0.5 rounded">
            PDF Standard • SHA-256 Sealed
          </span>
        </div>

        {/* Farm & Crop Option Dropdowns */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
          <div className="space-y-1">
            <label className="font-semibold text-slate-700">Target Holding</label>
            <select
              value={activeFarmId || 1}
              onChange={(e) => setActiveFarmId(Number(e.target.value))}
              className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-lg focus:outline-emerald-600 cursor-pointer font-medium text-slate-800"
            >
              {farms.map((f) => (
                <option key={f.id} value={f.id}>
                  {f.name} ({f.total_area_hectares} ha)
                </option>
              ))}
            </select>
          </div>

          <div className="space-y-1">
            <label className="font-semibold text-slate-700">Crop Cultivar</label>
            <select
              value={cropType}
              onChange={(e) => setCropType(e.target.value)}
              className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-lg focus:outline-emerald-600 cursor-pointer font-medium text-slate-800"
            >
              <option value="Winter Wheat (Triticum aestivum)">Winter Wheat (Triticum aestivum)</option>
              <option value="Hybrid Maize (Zea mays Pioneer P3501)">Hybrid Maize (Zea mays)</option>
              <option value="Basmati Rice (Oryza sativa Pusa-1121)">Basmati Rice (Oryza sativa)</option>
              <option value="Soybean (Glycine max JS-335)">Soybean (Glycine max)</option>
            </select>
          </div>
        </div>

        {/* Report Section Inclusion Check Options */}
        <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-2.5 text-xs">
          <span className="font-semibold text-slate-900 block text-[11px] uppercase tracking-wider">
            Certificate Section Inclusions (Check Options)
          </span>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2 text-xs">
            <label className="flex items-center gap-2 cursor-pointer text-slate-700 hover:text-slate-900 select-none">
              <input
                type="checkbox"
                checked={incSummary}
                onChange={(e) => setIncSummary(e.target.checked)}
                className="w-4 h-4 rounded border-slate-300 text-purple-700 focus:ring-purple-600 accent-purple-700 cursor-pointer"
              />
              <span>Executive Farm Summary</span>
            </label>
            <label className="flex items-center gap-2 cursor-pointer text-slate-700 hover:text-slate-900 select-none">
              <input
                type="checkbox"
                checked={incYield}
                onChange={(e) => setIncYield(e.target.checked)}
                className="w-4 h-4 rounded border-slate-300 text-purple-700 focus:ring-purple-600 accent-purple-700 cursor-pointer"
              />
              <span>Quantum Yield Forecast (QSVR)</span>
            </label>
            <label className="flex items-center gap-2 cursor-pointer text-slate-700 hover:text-slate-900 select-none">
              <input
                type="checkbox"
                checked={incSatellite}
                onChange={(e) => setIncSatellite(e.target.checked)}
                className="w-4 h-4 rounded border-slate-300 text-purple-700 focus:ring-purple-600 accent-purple-700 cursor-pointer"
              />
              <span>Sentinel-2 NDVI Canopy Vigor</span>
            </label>
            <label className="flex items-center gap-2 cursor-pointer text-slate-700 hover:text-slate-900 select-none">
              <input
                type="checkbox"
                checked={incWeather}
                onChange={(e) => setIncWeather(e.target.checked)}
                className="w-4 h-4 rounded border-slate-300 text-purple-700 focus:ring-purple-600 accent-purple-700 cursor-pointer"
              />
              <span>Visual Crossing Weather Analysis</span>
            </label>
            <label className="flex items-center gap-2 cursor-pointer text-slate-700 hover:text-slate-900 select-none">
              <input
                type="checkbox"
                checked={incNutrients}
                onChange={(e) => setIncNutrients(e.target.checked)}
                className="w-4 h-4 rounded border-slate-300 text-purple-700 focus:ring-purple-600 accent-purple-700 cursor-pointer"
              />
              <span>Liebig Nutrient Recommendations</span>
            </label>
            <label className="flex items-center gap-2 cursor-pointer text-slate-700 hover:text-slate-900 select-none">
              <input
                type="checkbox"
                checked={incKernelMatrix}
                onChange={(e) => setIncKernelMatrix(e.target.checked)}
                className="w-4 h-4 rounded border-slate-300 text-purple-700 focus:ring-purple-600 accent-purple-700 cursor-pointer"
              />
              <span>Raw Hilbert Quantum Matrix</span>
            </label>
            <label className="flex items-center gap-2 cursor-pointer text-slate-700 hover:text-slate-900 select-none">
              <input
                type="checkbox"
                checked={incSha256}
                onChange={(e) => setIncSha256(e.target.checked)}
                className="w-4 h-4 rounded border-slate-300 text-purple-700 focus:ring-purple-600 accent-purple-700 cursor-pointer"
              />
              <span>Cryptographic SHA-256 Seal</span>
            </label>
          </div>
        </div>

        <div className="pt-2">
          <button
            onClick={handleGenerateReport}
            disabled={generating}
            className="inline-flex items-center gap-2 bg-emerald-700 hover:bg-emerald-800 text-white font-semibold text-xs px-4 py-2.5 rounded-xl shadow-sm transition-all disabled:opacity-50 cursor-pointer"
          >
            {generating ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin" />
                <span>Compiling Agronomic Audit PDF...</span>
              </>
            ) : (
              <>
                <FileText className="w-4 h-4" />
                <span>Generate Audit Report</span>
              </>
            )}
          </button>
        </div>

        {reportResult && (
          <div className="mt-4 p-5 bg-purple-50/50 rounded-xl border border-purple-200 text-xs space-y-3">
            <div className="flex items-center justify-between">
              <span className="font-semibold text-purple-950">{reportResult.title}</span>
              <span className="font-mono text-[10px] text-purple-700 bg-purple-100 px-2 py-0.5 rounded">
                Report #{reportResult.report_id}
              </span>
            </div>

            <p className="text-purple-900 leading-relaxed font-mono text-[11px] bg-white p-3 rounded-lg border border-purple-100">
              {reportResult.summary}
            </p>

            <div className="flex items-center justify-between pt-2">
              <span className="text-slate-400 font-mono text-[10px]">
                Generated: {new Date(reportResult.generated_at).toLocaleString()}
              </span>
              <a
                href={`${API_BASE_URL.replace("/api/v1", "")}${reportResult.download_pdf_url}`}
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-1.5 bg-purple-700 hover:bg-purple-800 text-white font-semibold text-xs px-3 py-1.5 rounded-lg transition-colors shadow-xs"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Export Report (PDF)</span>
              </a>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
